window.WMM_VALUES = [
  { id: "action", label: "Action" },
  { id: "beauty", label: "Beauty" },
  { id: "being", label: "Being" },
  { id: "belonging-connection", label: "Belonging / Connection" },
  { id: "dignity", label: "Dignity" },
  { id: "feeling", label: "Feeling" },
  { id: "freedom", label: "Freedom" },
  { id: "goodness", label: "Goodness" },
  { id: "happiness", label: "Happiness" },
  { id: "health", label: "Health" },
  { id: "justice", label: "Justice" },
  { id: "knowledge", label: "Knowledge" },
  { id: "love", label: "Love" },
  { id: "meaning", label: "Meaning" },
  { id: "money", label: "Money" },
  { id: "order", label: "Order" },
  { id: "peace", label: "Peace" },
  { id: "pleasure", label: "Pleasure" },
  { id: "power", label: "Power" },
  { id: "resources", label: "Resources" },
  { id: "thought", label: "Thought" },
  { id: "time", label: "Time" },
  { id: "truth", label: "Truth" },
  { id: "war", label: "War" },
  { id: "wisdom", label: "Wisdom" },
];

window.WMM_STARTING_VALUE_IDS = ["truth", "beauty", "goodness", "action", "being", "dignity", "belonging-connection", "feeling", "freedom", "health", "happiness", "justice", "knowledge", "love", "meaning", "money", "order", "peace", "pleasure", "power", "resources", "thought", "time", "war", "wisdom"];
